import Head from 'next/head'
import Image from 'next/image'

import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from '@ant-design/icons';
import { Layout, Menu, theme } from 'antd';
import React ,{ useState } from 'react'
import IUniContent from './content';
import IUniHeader from './header';
import IUniSider from './sider';

const { Header, Sider, Content } = Layout;

export default function IUniLayout({children} : any){
    const [collapsed, setCollapsed] = useState(false);
    const [pageTitle, setPageTitle] = useState("");

    const { token: { colorBgContainer },} = theme.useToken();
    const toggleCollapse = () => { setCollapsed(() => !collapsed) };
    const handlePageTitle = (title:string) => { setPageTitle(() => title)};

    return(
      <>
        <Head>
          <title>iUniverse</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
        <IUniSider collapsed={collapsed} handlePageTitle={handlePageTitle}/>
        <Layout className="site-layout" style={{minHeight:'100vh'}}>
          <IUniHeader 
            toggleCollapse={toggleCollapse} 
            collapsed={collapsed}
            pageTitle={pageTitle} />  
          <IUniContent page={children} />
        </Layout>
      </Layout>
      </>
    )
}